'use strict';
const width = 3.5;
const height = 4.8;
const area = width * height;
console.log('value of area: ' + area);
console.log('type of area: ' + typeof area);
const bill = 115.04;
const payment = 141.0;
const change = bill - payment;
console.log('value of change: ' + change);
console.log('type of change: ' + typeof change);
const quizzes = 80;
const midterm = 92;
const final = 98;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ' + grade);
console.log('type of grade: ' + typeof grade);
const firstName = 'Jimmy';
const lastName = 'Tran';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName: ' + fullName);
console.log('type of fullName: ' + typeof fullName);
const pH = Math.floor(Math.random() * 15);
const isAcidic = pH < 7;
console.log('pH value: ' + pH);
console.log('value of isAcidic: ' + isAcidic);
console.log('type of isAcidic: ' + typeof isAcidic);
const headCount = 15;
const isSparta = headCount > 300;
console.log('value of isSparta: ' + isSparta);
console.log('type of isSparta: ' + typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto: ' + motto);
console.log('type of motto: ' + typeof motto);
